dist: bionic
language: python
sudo: false
arch:
- amd64
- ppc64le
- s390x
git:
   depth: 1
python:
- 3.7
- 3.8
- pypy3
# Disable version pypy3 for ppc64le
jobs:
    exclude:
     - arch: ppc64le
       python: pypy3
     - arch: s390x
       python: pypy3
env:
- secure: "EhG2uSD2m1eGxuL2HeQewJJx7MVL4WpjrxyfiUBEgsApemD1yKJPjUnLwAyd\nbPi5HJx5ySm1TTRSvj6/yP85YLYTaJHA8OabKk7p0wFW294qcrYIDGovU7NL\n3YOqZmqN+S3XOBGFCOnByxE+pcxxWW/3/I09EgeW7D6tBPh67G0="
before_install:
  - >
    if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" || "$TRAVIS_CPU_ARCH" == "s390x" ]]; then
      sudo apt-get update;
      sudo apt-get -y install libmagickwand-dev;
    fi 
install:
- echo $TRAVIS_PYTHON_VERSION
- pip install -U pytest pytest-xdist coveralls
- >
    if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then
      pip install 'pytest-cov>=1.8.0';
    fi
- >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      pip install --upgrade setuptools;
    fi
- pip install -e .[test] --upgrade
script:
- python -mwand.version --verbose
- >
    if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      pytest --skip-pdf --boxed --durations=20;
    else
      pytest --skip-pdf --cov wand --boxed --durations=20;
    fi
after_success:
- coveralls
